apiVersion: apps/v1
kind: Deployment
metadata:
  name: vegn-deployment
  labels:
    app: vegn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vegn
  template:
    metadata:
      labels:
        app: vegn
    spec:
      containers:
      - name: vegn
        image: ashkarax/vegn-server:latest
        ports:
        - containerPort: 8080
        env:
        - name: DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: DBHOST
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-host

---

apiVersion: v1
kind: Service
metadata:
  name: vegn-service
spec:
  type: NodePort
  selector:
    app: vegn
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
